packages:
  - examples/*
  - fixtures/*
overrides:
  playwright: ^1.63.0
  vite: ^8.2.2
  vitest: ^5.0.2
  '@vitest/browser-playwright': ^5.0.2
allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  vue-demi: true
