packages:
  - examples/*
  - fixtures/*
overrides:
  playwright: ^1.62.1
  vite: ^8.2.1
  vitest: ^4.1.10
  '@vitest/browser-playwright': ^4.1.10
allowBuilds:
  esbuild: true
  msw: true
  sharp: true
  vue-demi: true
